### ISSUE TITLE
Crash on loading libpng16.so

### ISSUE THREAD

**Issue by BrianOn99** [naman14/Arcade#2]
This app is a great idea, but does not work for me with many attempts.

Sure, I am running the app on `armeabi-v7a` cpu.

Fresh download from google play, it crash when begin styling:
```
E/AndroidRuntime(12631): java.lang.UnsatisfiedLinkError: dlopen failed: could not load library "libpng16.so.16" needed by "libarcade.so"; caused by library "libpng16.so.16" not found
E/AndroidRuntime(12631): 	at java.lang.Runtime.loadLibrary(Runtime.java:371)
E/AndroidRuntime(12631): 	at java.lang.System.loadLibrary(System.java:989)
E/AndroidRuntime(12631): 	at com.naman14.arcade.library.Arcade.<clinit>(Arcade.java:31)
E/AndroidRuntime(12631): 	at com.naman14.arcade.library.ArcadeBuilder.build(ArcadeBuilder.java:164)
E/AndroidRuntime(12631): 	at com.naman14.arcade.ArcadeService.beginStyling(ArcadeService.java:52)
E/AndroidRuntime(12631): 	at com.naman14.arcade.ArcadeService.onHandleIntent(ArcadeService.java:36)
E/AndroidRuntime(12631): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
E/AndroidRuntime(12631): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(12631): 	at android.os.Looper.loop(Looper.java:145)
E/AndroidRuntime(12631): 	at android.os.HandlerThread.run(HandlerThread.java:61)
```

The same crash when I git clone and ndk-build.

I to ported from ndk-build to cmake, and finally get pass that error.  However, it crashed later with:
```
11-23 10:21:10.827 2969-8545/com.naman14.arcade I/Arcade: error loading module 'libpng' from file '/data/app/com.naman14.arcade-1/lib/arm/libpng.so':
                                                          	undefined symbol: luaopen_libpng
```
,which occurs on `neural_style.lua` line 55.

I noticed that libpng.so is the same as libpng16.so, and there is no symbol `luaopen_libpng` in the binary, so I go to torch-android in github and build it myself.  I found `luaopen_libpng`
 in the resulting .so, but replacing the libpng.so still give that error.

How did you ever run the app successfully?

I am interested in this project and I would like to contribute to it after I get pass this error.  I could share my branch if needed.

**Comment by sadaharusong** [comment]
Hello, I use libpng.so instead libpng16.so to solve the problem . But now, I have a new problem, it is missing libarcade.so in the file.  Do you miss the file ?

**Comment by BrianOn99** [comment]
I don't have this file.

**Comment by sadaharusong** [comment]
Well, Did you find other repository like this ? If you find , could you please share to me ?

**Comment by BrianOn99** [comment]
@sadaharusong : No. If you find one, please also share it with me 😛

**Comment by sadaharusong** [comment]
@BrianOn99 Google opened a library of open source recently , named tensorflow . You can see it on github        or go to official website to see it . It's great !

**Comment by sadaharusong** [comment]
@BrianOn99 Could you please find this file path  Arcade\arcade\src\main\obj\local\armeabi-v7a  . The libarcade.so maybe in there , I didn't build it success.

**Comment by huyn** [comment]
Same to me.
`System.loadLibrary("png16");` and `System.loadLibrary("png");` meet the same error:
`error loading module 'libpng' from file '/data/app/com.aube.artflow-1/lib/arm/libpng.so':
                                                        	undefined symbol: luaopen_libpng`

**Comment by BrianOn99** [comment]
I have deleted my build and have no time to try it again.

**Comment by sadaharusong** [comment]
@huyn @BrianOn99 I talk to the author . He will try to revisit the project.
